### PR TITLE
add -C option to select a cookie jar file for libcurl

### PR DESCRIPTION
**Pull request by upavixie**
there exist cookie-based authentication schemes, make sure dnsdbq can access them.

### CODE REVIEW

**Comment by djw1149** [comment]
I suggest using an environment variable, rather than a command-line option, for specifying the cookie jar.  The value should presumably vary little, so is better suited for the environment.  This will save -C for more timely options.
Maybe use "DNSDB_CURL_COOKIE_FILE"?

**Comment by upavixie** [comment]
while there may be some utility in specifying a different cookie file for each pdns service, i chose to make this as much as possible like the curl(1) command, whose man page says:

```
       -b, --cookie <data|filename>
              (HTTP) Pass the data to the HTTP server in the Cookie header. It
              is supposedly the data previously received from the server in a
              "Set-Cookie:" line. The data should be in the format
              "NAME1=VALUE1; NAME2=VALUE2". This makes curl use the cookie
              header with this content explicitly in all outgoing request(s).
              If multiple requests are done due to authentication, followed
              redirects or similar, they all get this cookie passed on.

              If no '=' symbol is used in the argument, it is instead treated
              as a filename to read previously stored cookie from. This option
              also activates the cookie engine which makes curl record
              incoming cookies, which may be handy if you are using this in
              combination with the -L, --location option or do multiple URL
              transfers on the same invoke. If the file name is exactly a
              minus ("-"), curl instead reads the contents from stdin.

              The file format of the file to read cookies from should be plain
              HTTP headers (Set-Cookie style) or the Netscape/Mozilla cookie
              file format.
```

**Comment by djw1149** [comment]
Please add a reference in the man page to https://curl.se/docs/http-cookies.html or a similar doc of the cookie format.
Add a note that dnsdbq does not provide a way to generate a cookie file.

Then it is ok to merge this with a subminor version update in globals.h.

**Review by djw1149 — CHANGES_REQUESTED** [review]
See comments in Conversation

**Comment by djw1149** [comment]
s/analagous/analogous

**Pull request merged**
