### PR TITLE
fix no-newline-eof bug in -f for jonas; add -f -f support (verbose ba…

### PR DESCRIPTION
**Pull request by vixie**
this adds a ++ indicator to the front of each answer in -f mode, enabled by saying -f -f.

-f -m has no framing, since outputs are merged at newline level. -f -f m is not supported (yet.)

there's also a bug fix here, to permit batch files that don't have a newline before EOF.

### CODE REVIEW

**Comment by djw1149** [comment]
What is the expected behavior of -m in the following situation?
```
$ cat test1.batch 
rrset/name/bbn.com
rdata/ip/128.89.0.1,16
rdata/ip/46.0.0.0,16

$ dnsdbq < test1.batch -f  -l 2 -j
{"count":356,"time_first":1573846916,"time_last":1576445811,"rrname":"bbn.com.","rrtype":"A","bailiwick":"bbn.com.","rdata":["192.1.122.24"]}
{"count":105588,"time_first":1573842279,"time_last":1576442761,"rrname":"bbn.com.","rrtype":"NS","bailiwick":"com.","rdata":["bos-service1.raytheon.com.","dfw-service1.raytheon.com.","lax-service1.raytheon.com."]}
--
{"count":79,"time_first":1573959086,"time_last":1576391781,"rrname":"spooler2.bbn.com.","rrtype":"A","rdata":"128.89.1.199"}
{"count":79,"time_first":1573959086,"time_last":1576391781,"rrname":"spooler1.bbn.com.","rrtype":"A","rdata":"128.89.2.34"}
--
{"count":11,"time_first":1573987406,"time_last":1576408080,"rrname":"atelierraeber.ch.","rrtype":"A","rdata":"46.0.0.0"}
{"count":2,"time_first":1574093885,"time_last":1574093885,"rrname":"46.0.0.1.xip.io.","rrtype":"A","rdata":"46.0.0.1"}
--

$ dnsdbq < test1.batch -f  -l 2 -j -m
{"count":356,"time_first":1573846916,"time_last":1576445811,"rrname":"bbn.com.","rrtype":"A","bailiwick":"bbn.com.","rdata":["192.1.122.24"]}
{"count":105588,"time_first":1573842279,"time_last":1576442761,"rrname":"bbn.com.","rrtype":"NS","bailiwick":"com.","rdata":["bos-service1.raytheon.com.","dfw-service1.raytheon.com.","lax-service1.raytheon.com."]}
```

**Comment by vixie** [comment]
On Sunday, 15 December 2019 23:26:14 UTC djw1149 wrote:
> What is the expected behavior of -m in the following situation?
> ```
> $ cat test1.batch
> rrset/name/bbn.com
> rdata/ip/128.89.0.1,16
> rdata/ip/46.0.0.0,16
...
> $ dnsdbq < test1.batch -f  -l 2 -j -m
> {"count":356,"time_first":1573846916,"time_last":1576445811,"rrname":"bbn.co
> m.","rrtype":"A","bailiwick":"bbn.com.","rdata":["192.1.122.24"]}
> {"count":105588,"time_first":1573842279,"time_last":1576442761,"rrname":"bb
> n.com.","rrtype":"NS","bailiwick":"com.","rdata":["bos-service1.raytheon.com
> .","dfw-service1.raytheon.com.","lax-service1.raytheon.com."]} ```

-l should affect only the number of results per fetch, not the output size. 
this was an old bug but i have no objection to fixing it as part of this PR.

i have corrected the code and documentation on the branch. you can see the 
delta with "git diff newframing2 newframing3".

-- 
Paul

**Comment by djw1149** [comment]
How should errors from a particular batch line's query be handled?
Given:
```
$ cat test3.batch 
rrset/name
rrset/name/bbn.com
rdata/ip/128.89.0.1,16
rdata/ip/46.0.0.0,16
rrset/bogus/*.*
rrset/name/*.*
```
The raw output to both stdout and stderr looks nice:
```
$ dnsdbq < test3.batch -f  -l 2 -j   -f    
++ rrset/name
libcurl: 400 (https://api-dnsdb.dev.fsi.io/lookup/rrset/name?swclient=dnsdbq&version=1.4&limit=2)
libcurl: Error: unable to parse request
--
++ rrset/name/bbn.com
{"count":347,"time_first":1573957301,"time_last":1576485751,"rrname":"bbn.com.","rrtype":"A","bailiwick":"bbn.com.","rdata":["192.1.122.24"]}
{"count":105086,"time_first":1573925926,"time_last":1576497163,"rrname":"bbn.com.","rrtype":"NS","bailiwick":"com.","rdata":["bos-service1.raytheon.com.","dfw-service1.raytheon.com.","lax-service1.raytheon.com."]}
--
++ rdata/ip/128.89.0.1,16
{"count":81,"time_first":1573959086,"time_last":1576464985,"rrname":"spooler2.bbn.com.","rrtype":"A","rdata":"128.89.1.199"}
{"count":81,"time_first":1573959086,"time_last":1576464985,"rrname":"spooler1.bbn.com.","rrtype":"A","rdata":"128.89.2.34"}
--
++ rdata/ip/46.0.0.0,16
{"count":11,"time_first":1573987406,"time_last":1576408080,"rrname":"atelierraeber.ch.","rrtype":"A","rdata":"46.0.0.0"}
{"count":2,"time_first":1574093885,"time_last":1574093885,"rrname":"46.0.0.1.xip.io.","rrtype":"A","rdata":"46.0.0.1"}
--
++ rrset/bogus/*.*
libcurl: 400 (https://api-dnsdb.dev.fsi.io/lookup/rrset/bogus/*.*?swclient=dnsdbq&version=1.4&limit=2)
libcurl: Error: unable to parse request
--
++ rrset/name/*.*
libcurl: 404 (https://api-dnsdb.dev.fsi.io/lookup/rrset/name/*.*?swclient=dnsdbq&version=1.4&limit=2)
please note: 404 might just mean that no records matched the search criteria
libcurl: Error: no results found for query.
--
```

But if you only look at stderr, you see:
```
$ dnsdbq < test3.batch -f  -l 2 -j   -f  1>/dev/null
libcurl: 400 (https://api-dnsdb.dev.fsi.io/lookup/rrset/name?swclient=dnsdbq&version=1.4&limit=2)
libcurl: Error: unable to parse request
libcurl: 400 (https://api-dnsdb.dev.fsi.io/lookup/rrset/bogus/*.*?swclient=dnsdbq&version=1.4&limit=2)
libcurl: Error: unable to parse request
libcurl: 404 (https://api-dnsdb.dev.fsi.io/lookup/rrset/name/*.*?swclient=dnsdbq&version=1.4&limit=2)
please note: 404 might just mean that no records matched the search criteria
libcurl: Error: no results found for query.
```
My suggestion is some sort of error message on the `--` lines when run with the double -f -f.  Perhaps like `-- Error: unable to parse request` and `-- Error: no results found for query.`

**Comment by vixie** [comment]
On Monday, 16 December 2019 14:09:03 UTC djw1149 wrote:
> How should errors from a particular batch line's query be handled?
...
> My suggestion is some sort of error message on the `--` lines when run with
> the double -f -f.  Perhaps like `-- Error: unable to parse request` and `--
> Error: no results found for query.`

ok, done. required some reorganization. same branch; tag is newframing4.

-- 
Paul

**Pull request merged**
